### PR TITLE
new minor version

### PR DESCRIPTION
**Pull request by chancehudson**
I pushed a new minor version including an optional second argument for retrieving additional state elements. chancehudson/poseidon-lite#3

### CODE REVIEW

**Comment by chancehudson** [comment]
We need to figure out a way to consolidate these repos, or operate both of them simultaneously. I think they have few enough changes that we can keep both up as mirrors and sync them as needed. wyt @cedoor ?

**Review by cedoor — APPROVED** [review]
ACK 👍🏽

**Comment by chancehudson** [comment]
What is "ACK??

**Comment by cedoor** [comment]
> What is "ACK"?

https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#conceptual-review
https://github.com/bitcoin/bitcoin/issues/6100

Seen used by @sripwoud :D

**Comment by chancehudson** [comment]
Haha, cool

**Pull request merged**
